In [29]:
import pandas as pd

df = pd.read_csv('/Users/levinschily/Desktop/IRONHACK/Week3/Project2/World-happiness-report/2019.csv')
df.head(5)

df2 = pd.read_csv('/Users/levinschily/Desktop/IRONHACK/Week3/Project2/Economic-Freedom/economic_freedom_index2019_data.csv', encoding='latin1')
df

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

In [27]:
df2

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,...,Afghanistan,35.5,$69.6,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
1,2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,...,Albania,2.9,$36.0,3.9,2.5,"$12,507",13.9,2.0,"1,119.1",71.2
2,3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,...,Algeria,41.5,$632.9,2.0,3.1,"$15,237",10.0,5.6,"1,203.0",25.8
3,4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,...,Angola,28.2,$190.3,0.7,2.9,"$6,753",8.2,31.7,"-2,254.5",65.3
4,5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,...,Argentina,44.1,$920.2,2.9,0.7,"$20,876",8.7,25.7,"11,857.0",52.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,179,Venezuela,Venezuela,Americas,179.0,32.0,25.9,7.6,13.1,7.9,...,Venezuela,31.4,$380.7,-14.0,-7.8,"$12,114",7.7,1087.5,-68.0,34.9
182,180,Vietnam,Vietnam,Asia-Pacific,128.0,30.0,55.3,49.8,40.3,34.0,...,Vietnam,93.6,$647.4,6.8,6.2,"$6,913",2.1,3.5,"14,100.0",58.2
183,181,Yemen,Yemen,Middle East and North Africa,NaN,NaN,NaN,19.6,22.2,20.3,...,Yemen,30.0,$38.6,-13.8,-16.1,"$1,287",14.0,4.9,-269.9,141.0
184,182,Zambia,Zambia,Sub-Saharan Africa,138.0,27.0,53.6,45.0,35.6,32.3,...,Zambia,17.2,$68.9,3.6,4.0,"$3,996",7.8,6.6,"1,091.2",62.2
185,183,Zimbabwe,Zimbabwe,Sub-Saharan Africa,175.0,45.0,40.4,29.7,24.8,15.8,...,Zimbabwe,14.9,$34.0,3.0,2.6,"$2,283",5.0,1.3,289.4,78.4

In [25]:
df2.duplicated().sum()
df2.isna().sum()

CountryID                      0
Country Name                   0
WEBNAME                        0
Region                         0
World Rank                     6
Region Rank                    6
2019 Score                     6
Property Rights                1
Judical Effectiveness          1
Government Integrity           1
Tax Burden                     6
Gov't Spending                 3
Fiscal Health                  3
Business Freedom               1
Labor Freedom                  2
Monetary Freedom               2
Trade Freedom                  4
Investment Freedom             2
Financial Freedom              5
Tariff Rate (%)                4
Income Tax Rate (%)            3
Corporate Tax Rate (%)         3
Tax Burden % of GDP            7
Gov't Expenditure % of GDP     4
Country                        0
Population (Millions)          0
GDP (Billions, PPP)            1
GDP Growth Rate (%)            2
5 Year GDP Growth Rate (%)     3
GDP per Capita (PPP)           2
Unemployment (%)               5
Inflation (%)                  4
FDI Inflow (Millions)          5
Public Debt (% of GDP)         4
dtype: int64

In [37]:
df.columns = ['overall_rank', 'country_or_region', 'score', 'gdp_per_capita',
       'social_support', 'Healthy_life_expectancy',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption']

df2.columns = ['CountryID', 'country_or_region', 'WEBNAME', 'Region', 'World Rank',
       'Region Rank', '2019 Score', 'Property Rights', 'Judical Effectiveness',
       'Government Integrity', 'Tax Burden', "Gov't Spending", 'Fiscal Health',
       'Business Freedom', 'Labor Freedom', 'Monetary Freedom',
       'Trade Freedom', 'Investment Freedom ', 'Financial Freedom',
       'Tariff Rate (%)', 'Income Tax Rate (%)', 'Corporate Tax Rate (%)',
       'Tax Burden % of GDP', "Gov't Expenditure % of GDP", 'Country',
       'Population (Millions)', 'GDP (Billions, PPP)', 'GDP Growth Rate (%)',
       '5 Year GDP Growth Rate (%)', 'GDP per Capita (PPP)',
       'Unemployment (%)', 'Inflation (%)', 'FDI Inflow (Millions)',
       'Public Debt (% of GDP)']

In [39]:
merged_df = pd.merge(df, df2, on='country_or_region')
merged_df

,overall_rank,country_or_region,score,gdp_per_capita,social_support,Healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,CountryID,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,57,...,Finland,5.5,$244.0,3.0,0.8,"$44,333",8.6,0.8,"1,327.9",61.4
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,45,...,Denmark,5.7,$286.8,2.1,1.6,"$49,883",5.7,1.1,"-3,114.7",36.4
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,124,...,Norway,5.3,$380.0,1.8,1.6,"$71,831",4.2,1.9,"-8,296.9",36.7
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,73,...,Iceland,0.3,$17.6,3.6,4.4,"$51,842",2.8,1.8,-5.4,40.9
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,119,...,Netherlands,17.1,$916.1,3.1,1.8,"$53,635",4.8,1.3,"57,956.7",56.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,151,Yemen,3.380,0.287,1.163,0.463,0.143,0.108,0.077,181,...,Yemen,30.0,$38.6,-13.8,-16.1,"$1,287",14.0,4.9,-269.9,141.0
139,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411,137,...,Rwanda,11.8,$24.6,6.1,6.7,"$2,080",1.3,4.8,366.2,40.6
140,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147,162,...,Tanzania,50.0,$162.2,6.0,6.8,"$3,240",2.2,5.3,"1,180.4",38.2
141,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025,1,...,Afghanistan,35.5,$69.6,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
142,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035,31,...,Central African Republic,5.0,$3.4,4.0,-4.5,$677,6.0,3.8,17.2,53.4

In [41]:
merged_df = merged_df.drop(['CountryID', 'Tax Burden','WEBNAME', 'Region', 'World Rank','Region Rank', '2019 Score', 'Property Rights','Tax Burden % of GDP', "Gov't Expenditure % of GDP", 'Country','5 Year GDP Growth Rate (%)', 'GDP per Capita (PPP)','Unemployment (%)', 'Inflation (%)', 'FDI Inflow (Millions)', 'Public Debt (% of GDP)'], axis=1)

In [45]:
merged_df.columns

Index(['overall_rank', 'country_or_region', 'score', 'gdp_per_capita',
       'social_support', 'Healthy_life_expectancy',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption', 'Judical Effectiveness',
       'Government Integrity', 'Gov't Spending', 'Fiscal Health',
       'Business Freedom', 'Labor Freedom', 'Monetary Freedom',
       'Trade Freedom', 'Investment Freedom ', 'Financial Freedom',
       'Tariff Rate (%)', 'Income Tax Rate (%)', 'Corporate Tax Rate (%)',
       'Population (Millions)', 'GDP (Billions, PPP)', 'GDP Growth Rate (%)'],
      dtype='object')

In [51]:
merged_df = merged_df.drop(['Tariff Rate (%)', 'Income Tax Rate (%)', "GDP (Billions, PPP)", 'GDP Growth Rate (%)', 'Government Integrity', "Gov't Spending", 'Fiscal Health'], axis=1)
merged_df

,overall_rank,country_or_region,score,gdp_per_capita,social_support,Healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Judical Effectiveness,Business Freedom,Labor Freedom,Monetary Freedom,Trade Freedom,Investment Freedom,Financial Freedom,Corporate Tax Rate (%),Population (Millions)
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,81.2,89.4,50.3,84.8,86.0,85.0,80.0,20.0,5.5
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,77.8,90.7,86.4,84.1,86.0,90.0,80.0,23.5,5.7
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,81.2,89.4,53.7,75.4,83.2,75.0,60.0,23.0,5.3
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,63.8,88.4,64.1,81.7,87.0,85.0,70.0,20.0,0.3
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,74.7,81.4,60.3,84.0,86.0,90.0,80.0,25.0,17.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,151,Yemen,3.380,0.287,1.163,0.463,0.143,0.108,0.077,22.2,45.1,49.8,61.5,71.4,50.0,NaN,NaN,30.0
139,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411,83.2,56.2,82.2,76.1,70.4,60.0,40.0,30.0,11.8
140,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147,41.4,46.6,66.2,70.4,67.8,55.0,50.0,30.0,50.0
141,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025,29.6,49.2,60.4,76.7,66.0,10.0,10.0,20.0,35.5
142,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035,29.6,24.2,40.1,72.3,51.0,45.0,30.0,30.0,5.0

In [53]:
merged_df.columns

Index(['overall_rank', 'country_or_region', 'score', 'gdp_per_capita',
       'social_support', 'Healthy_life_expectancy',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption', 'Judical Effectiveness',
       'Business Freedom', 'Labor Freedom', 'Monetary Freedom',
       'Trade Freedom', 'Investment Freedom ', 'Financial Freedom',
       'Corporate Tax Rate (%)', 'Population (Millions)'],
      dtype='object')